services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: backend-container

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: frontend-container
